// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ONX.CRM.DAL.EF.Contexts;

namespace ONX.CRM.DAL.EF.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NecessaryPreKnowledge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            Cost = 360m,
                            Description = "HTML & CSS are two fundamental technologies that every web developer must master. HTML (Hypertext Markup Language) is responsible for the skeleton of a web page: the presence of text, images, tables, buttons, information filling forms and other elements of the user interface. CSS (Cascading Styles Sheet) allows you to transform the appearance of the site into a human-readable form. Knowing only these two technologies will already give you the opportunity to create effective and attractive web pages.",
                            SpecializationId = 1,
                            Title = "HTML5/CSS3"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 800m,
                            Description = "JavaScript is one of the most popular programming languages. You can't do without his knowledge in web development. In addition to the implementation of custom logic (FrontEnd), it is used in the development of server (BackEnd), game and mobile applications, to create scripts for test automation, and more. Learning JS is a good investment in the future, as the language will be useful for solving various problems and will be useful in any area of development.",
                            NecessaryPreKnowledge = "\"HTML & CSS\" course",
                            SpecializationId = 1,
                            Title = "JavaScript"
                        },
                        new
                        {
                            Id = 9,
                            Cost = 1200m,
                            Description = "Angular Developer is a front-end web application (FrontEnd) developer who uses Google's Angular as a framework to write efficient Single Page Applications (SPA) with a consistent interface. The web services Gmail, Forbes, Upwork, PayPal, Weather.com and many others have been built with Angular.Our training program is aimed at learning all the necessary tools for a successful start in this direction.",
                            NecessaryPreKnowledge = "\"JavaScript\" course",
                            SpecializationId = 1,
                            Title = "Angular"
                        },
                        new
                        {
                            Id = 10,
                            Cost = 1400m,
                            Description = "C # (si sharp) is an object-oriented programming language developed by Microsoft. The direct interest of such a large corporation in the language ensures that it continues to evolve and find applications in various industries. C Sharp has absorbed the best qualities, and also inherited the features of the syntax of Java and C ++. The language is used for web development, desktop and mobile applications. If you signed up for a course on C # in Minsk in order to learn how to create web projects, then in the future you need to master the .NET toolkit. Thanks to the huge amount of documentation, C # is quite easy to learn. And its own development environment Visual Studio, ready-made templates, modules, procedures make the language comfortable to use. After completing the basic course \"Programming in C #\", you can choose a direction for further development - to.",
                            SpecializationId = 2,
                            Title = "Programming on C#"
                        },
                        new
                        {
                            Id = 11,
                            Cost = 1900m,
                            Description = "ASP.NET is a Microsoft technology for creating websites, web services and applications. Due to its reliability, security and flexibility, it is actively used by large companies. The technology's standard libraries contain many modules, templates and procedures, which makes it convenient for developing and supporting large-scale projects. It is quite difficult to study ASP.NET in courses in Minsk, but those who cope with this task will have one of the highest salaries in the IT sphere.",
                            NecessaryPreKnowledge = "\"C # programming\" course",
                            SpecializationId = 2,
                            Title = "Industrial programming with ASP.NET"
                        },
                        new
                        {
                            Id = 12,
                            Cost = 1400m,
                            Description = "Java is a language that has not left all kinds of TOPs of popular programming languages for many years. With its help, various software solutions are created: from computer games and mobile applications for Android to software for banking systems and cloud storage. Reliability, power, efficiency and multi - platform are the main hallmarks of Java. If you want to work with a classic tool that can handle any task - Java is for you.",
                            SpecializationId = 3,
                            Title = "Industrial software development on Java"
                        },
                        new
                        {
                            Id = 13,
                            Cost = 1900m,
                            Description = "Java is a general-purpose programming language that is suitable for many tasks and can handle a variety of challenges. Do you want to learn how to use it effectively? Sign up for a Java web development course in Minsk. The program was created by the largest software developer EPAM Systems. Certified graduates of the course will receive an invitation to the EPAM Java lab to further move along the path of employment with the company.",
                            NecessaryPreKnowledge = "\"Industrial software development on Java\"  course",
                            SpecializationId = 3,
                            Title = "Java Web Development"
                        },
                        new
                        {
                            Id = 14,
                            Cost = 1400m,
                            Description = "C # (si sharp) is an object-oriented programming language developed by Microsoft. The direct interest of such a large corporation in the language ensures that it continues to evolve and find applications in various industries. C Sharp has absorbed the best qualities, and also inherited the features of the syntax of Java and C ++. The language is used for web development, desktop and mobile applications. If you signed up for a course on C # in Minsk in order to learn how to create web projects, then in the future you need to master the .NET toolkit. Thanks to the huge amount of documentation, C # is quite easy to learn. And its own development environment Visual Studio, ready-made templates, modules, procedures make the language comfortable to use. After completing the basic course \"Programming in C #\", you can choose a direction for further development - to.",
                            SpecializationId = 4,
                            Title = "Programming on C#"
                        },
                        new
                        {
                            Id = 15,
                            Cost = 1600m,
                            Description = "Unity is a modern game engine that allows you to create projects of any level. Deus Ex: The Fall, Assassin's Creed: Identity, Wasteland 2, HearthStone and thousands of other games are based on it. Thanks to the low entry threshold and the C # language, anyone can release the first game mechanics in a short time. The course \"Development of mobile games on the Unity engine\" in Minsk will allow you to realize your creative abilities in the field of creating games, master an interesting profession and find a job. During the learning process, students will create several prototypes of games and their own project.",
                            NecessaryPreKnowledge = "\"C # programming\" course",
                            SpecializationId = 4,
                            Title = "Development of mobile games on the Unity engine"
                        },
                        new
                        {
                            Id = 16,
                            Cost = 990m,
                            Description = "Working with relational databases and being able to write effective queries in SQL are important hard skills for many IT professionals. They are especially needed for those who want to build a successful career in the field of high technology as a back-end developer or move in the direction of Business Intelligence and data analytics. A course on relational databases and SQL in Minsk will help you get the necessary skills. The training program is developed by an IT company.",
                            SpecializationId = 5,
                            Title = "Relational databases and SQL"
                        },
                        new
                        {
                            Id = 17,
                            Cost = 2099m,
                            Description = "iOS is the world's second most popular mobile operating system for Apple devices. To simplify the process of developing applications for iOS, the company released the open source programming language Swift. It is an easier-to-read and error-tolerant alternative to Objective-C. Apple is for minimalism, so Swift has a simple syntax, easy to read and easy to write. After completing the iOS course in Minsk, you will be ready for an interview for the junior iOS developer position, you will be able to work in a mobile development team, apply the iOS SDK and Swift, and create your own applications for the App Store.",
                            SpecializationId = 6,
                            Title = "Comprehensive Course in iOS App Development"
                        });
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 15,
                            Number = "MR00-0012-FT04",
                            StartDate = new DateTime(2021, 11, 9, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 11,
                            Number = "MR00-5512-DT12",
                            StartDate = new DateTime(2021, 11, 9, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 10,
                            Number = "MR00-2671-FG10",
                            StartDate = new DateTime(2021, 12, 15, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 12,
                            Number = "MR00-2671-FG10",
                            StartDate = new DateTime(2021, 12, 9, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TeacherId = 2
                        });
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Homework")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Materials")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2021, 11, 9, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basic entities of the engine. Basic object manipulation. Features of using assets. Build the project.",
                            GroupId = 1,
                            Homework = "Install Unity. Build the project for mobile devices and PC",
                            Number = "01",
                            Topic = "Unity Editor"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2021, 11, 11, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Camera. Mesh, Material, Texture.",
                            GroupId = 1,
                            Homework = "Add mesh, material, texture to the project",
                            Number = "02",
                            Topic = "Basics of 3D"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2021, 11, 16, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Interface animations. Animations with Animator.",
                            GroupId = 1,
                            Homework = "Create any animation and add it to the project",
                            Number = "03",
                            Topic = "Animations"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2021, 11, 4, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Algorithms. Evolution of languages. C # language, general syntax concepts.",
                            GroupId = 2,
                            Homework = "Install the Visual Studio 2019. Create a console project and run it.",
                            Number = "01",
                            Topic = "Basics of programming"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2021, 11, 9, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Arithmetic. Relations. Logical. Appropriation. Bitwise. Using brackets. Division",
                            GroupId = 2,
                            Homework = "To install the Git. Create repository and do the first PR. Create a console project and output \"hello world\" to the console.",
                            Number = "02",
                            Topic = "C# Operators"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2021, 11, 11, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "One-dimensional arrays. Multidimensional arrays. Strings and the StringBuilder class. String comparison",
                            GroupId = 2,
                            Homework = "Create three string local variables. Make string concatenation. Output the result to the console.",
                            Number = "03",
                            Topic = "Arrays & Strings"
                        });
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "manager@mail.ru",
                            FirstName = "John",
                            LastName = "Smith",
                            Phone = "+375441183334"
                        });
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNGName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PNGName = "frontend-developer.png",
                            Title = "Frontend Developer"
                        },
                        new
                        {
                            Id = 2,
                            PNGName = "net-developer.png",
                            Title = ".NET Developer"
                        },
                        new
                        {
                            Id = 3,
                            PNGName = "java-developer.png",
                            Title = "Java Developer"
                        },
                        new
                        {
                            Id = 4,
                            PNGName = "game-developer.png",
                            Title = "Unity Developer"
                        },
                        new
                        {
                            Id = 5,
                            PNGName = "database-developer.png",
                            Title = "Database Developer"
                        },
                        new
                        {
                            Id = 6,
                            PNGName = "ios-developer.png",
                            Title = "iOS Developer"
                        });
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Email = "Medvedev1990@gmail.com",
                            FirstName = "Егор",
                            GroupId = 3,
                            LastName = "Медведев",
                            Phone = "+375441188802",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "Ershov9512@gmail.com",
                            FirstName = "Александр",
                            GroupId = 3,
                            LastName = "Ершов",
                            Phone = "+375441188803",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Email = "Nikitin01@gmail.com",
                            FirstName = "Роман",
                            GroupId = 3,
                            LastName = "Никитин",
                            Phone = "+375441188804",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "Sobolev11@gmail.com",
                            FirstName = "Сергей",
                            GroupId = 3,
                            LastName = "Соболев",
                            Phone = "+375441188805",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "Ryabov903@gmail.com",
                            FirstName = "Анна",
                            GroupId = 3,
                            LastName = "Рябова",
                            Phone = "+375441188806",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Email = "Polyakov99@gmail.com",
                            FirstName = "Алексей",
                            GroupId = 3,
                            LastName = "Поляков",
                            Phone = "+375441188807",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Email = "Cvetkova41@gmail.com",
                            FirstName = "Надежда",
                            GroupId = 3,
                            LastName = "Цветкова",
                            Phone = "+375441188808",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Email = "Danilova355@gmail.com",
                            FirstName = "Виктория",
                            GroupId = 3,
                            LastName = "Данилова",
                            Phone = "+375441188809",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Email = "Jukov07@gmail.com",
                            FirstName = "Антон",
                            GroupId = 3,
                            LastName = "Жуков",
                            Phone = "+375441188810",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Email = "Frolov855@gmail.com",
                            FirstName = "Геннадий",
                            GroupId = 3,
                            LastName = "Фролов",
                            Phone = "+375441188811",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Email = "Lapin0110@gmail.com",
                            FirstName = "Виктор",
                            GroupId = 3,
                            LastName = "Лапин",
                            Phone = "+375441188812",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Email = "Juravliov43@gmail.com",
                            FirstName = "Светлана",
                            GroupId = 3,
                            LastName = "Журавлёва",
                            Phone = "+375441188813",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Email = "Nikolayev61@gmail.com",
                            FirstName = "Роман",
                            GroupId = 3,
                            LastName = "Николаев",
                            Phone = "+375441188814",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Email = "Krylov96@gmail.com",
                            FirstName = "Сергей",
                            GroupId = 3,
                            LastName = "Крылов",
                            Phone = "+375441188815",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Email = "Maksimov77@gmail.com",
                            FirstName = "Максим",
                            GroupId = 3,
                            LastName = "Максимов",
                            Phone = "+375441188816",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            Email = "Sidorov610@gmail.com",
                            FirstName = "Егор",
                            GroupId = 3,
                            LastName = "Сидоров",
                            Phone = "+375441188817",
                            Type = 1
                        },
                        new
                        {
                            Id = 18,
                            Email = "Osipov0990@gmail.com",
                            FirstName = "Александр",
                            GroupId = 3,
                            LastName = "Осипов",
                            Phone = "+375441188818",
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            Email = "Belousov78@gmail.com",
                            FirstName = "Евгений",
                            GroupId = 3,
                            LastName = "Белоусов",
                            Phone = "+375441188819",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            Email = "Fedotov88@gmail.com",
                            FirstName = "Андрей",
                            GroupId = 3,
                            LastName = "Федотов",
                            Phone = "+375441188820",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            Email = "Dorofeyev45@gmail.com",
                            FirstName = "Виталий",
                            GroupId = 1,
                            LastName = "Дорофеев",
                            Phone = "+375441188821",
                            Type = 2
                        },
                        new
                        {
                            Id = 22,
                            Email = "Egorov212@gmail.com",
                            FirstName = "Василий",
                            GroupId = 1,
                            LastName = "Егоров",
                            Phone = "+375441188822",
                            Type = 2
                        },
                        new
                        {
                            Id = 23,
                            Email = "Matveyev67@gmail.com",
                            FirstName = "Владислав",
                            GroupId = 1,
                            LastName = "Матвеев",
                            Phone = "+375441188823",
                            Type = 2
                        },
                        new
                        {
                            Id = 24,
                            Email = "Bobrova72@gmail.com",
                            FirstName = "Анастасия",
                            GroupId = 1,
                            LastName = "Боброва",
                            Phone = "+375441188824",
                            Type = 2
                        },
                        new
                        {
                            Id = 25,
                            Email = "Dmitrieva1221@gmail.com",
                            FirstName = "Наталья",
                            GroupId = 1,
                            LastName = "Дмитриева",
                            Phone = "+375441188825",
                            Type = 2
                        },
                        new
                        {
                            Id = 26,
                            Email = "Kalinin45@gmail.com",
                            FirstName = "Сергей",
                            GroupId = 2,
                            LastName = "Калинин",
                            Phone = "+375441188826",
                            Type = 3
                        },
                        new
                        {
                            Id = 27,
                            Email = "Anisimov987@gmail.com",
                            FirstName = "Алексей",
                            GroupId = 2,
                            LastName = "Анисимов",
                            Phone = "+375441188827",
                            Type = 3
                        },
                        new
                        {
                            Id = 28,
                            Email = "Antonov543@gmail.com",
                            FirstName = "Александр",
                            GroupId = 2,
                            LastName = "Антонов",
                            Phone = "+375441188828",
                            Type = 3
                        },
                        new
                        {
                            Id = 29,
                            Email = "Sokolova1212@gmail.com",
                            FirstName = "Екатерина",
                            GroupId = 2,
                            LastName = "Соколова",
                            Phone = "+375441188829",
                            Type = 3
                        },
                        new
                        {
                            Id = 30,
                            Email = "Timofeev22@gmail.com",
                            FirstName = "Виталий",
                            GroupId = 2,
                            LastName = "Тимофеев",
                            Phone = "+375441188830",
                            Type = 3
                        },
                        new
                        {
                            Id = 1,
                            Email = "student@mail.ru",
                            FirstName = "Alex",
                            GroupId = 1,
                            LastName = "Lazarev",
                            Phone = "+375441188801",
                            Type = 1
                        });
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.StudentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "",
                            CourseId = 11,
                            Created = new DateTime(2021, 7, 15, 13, 17, 0, 0, DateTimeKind.Unspecified),
                            Email = "Nesterov23@gmail.com",
                            FirstName = "Андрей",
                            LastName = "Нестеров",
                            Phone = "+375441188132",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Comments = "",
                            CourseId = 11,
                            Created = new DateTime(2021, 7, 23, 20, 57, 0, 0, DateTimeKind.Unspecified),
                            Email = "Haritonov432@gmail.com",
                            FirstName = "Роман",
                            LastName = "Харитонов",
                            Phone = "+375441188365",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Comments = "",
                            CourseId = 11,
                            Created = new DateTime(2021, 8, 23, 8, 13, 0, 0, DateTimeKind.Unspecified),
                            Email = "Agafonov440@gmail.com",
                            FirstName = "Аркадий",
                            LastName = "Агафонов",
                            Phone = "+375441145830",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Comments = "",
                            CourseId = 11,
                            Created = new DateTime(2021, 9, 4, 23, 15, 0, 0, DateTimeKind.Unspecified),
                            Email = "Muraviov438@gmail.com",
                            FirstName = "Алексей",
                            LastName = "Муравьёв",
                            Phone = "+375441185430",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Comments = "",
                            CourseId = 11,
                            Created = new DateTime(2021, 7, 27, 20, 5, 0, 0, DateTimeKind.Unspecified),
                            Email = "Larionova85@gmail.com",
                            FirstName = "Ангелина",
                            LastName = "Ларионова",
                            Phone = "+375441348830",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Comments = "",
                            CourseId = 15,
                            Created = new DateTime(2021, 8, 15, 19, 44, 0, 0, DateTimeKind.Unspecified),
                            Email = "Fedoseyev86@gmail.com",
                            FirstName = "Денис",
                            LastName = "Федосеев",
                            Phone = "+375441675830",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Comments = "",
                            CourseId = 15,
                            Created = new DateTime(2021, 9, 3, 22, 36, 0, 0, DateTimeKind.Unspecified),
                            Email = "Zimin984@gmail.com",
                            FirstName = "Николай",
                            LastName = "Зимин",
                            Phone = "+375441186730",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Comments = "",
                            CourseId = 15,
                            Created = new DateTime(2021, 8, 20, 21, 17, 0, 0, DateTimeKind.Unspecified),
                            Email = "Pahomov43@gmail.com",
                            FirstName = "Максим",
                            LastName = "Пахомов",
                            Phone = "+375441188554",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Comments = "",
                            CourseId = 15,
                            Created = new DateTime(2021, 8, 3, 15, 35, 0, 0, DateTimeKind.Unspecified),
                            Email = "Shubin69@gmail.com",
                            FirstName = "Геннадий",
                            LastName = "Шубин",
                            Phone = "+375441188896",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Comments = "",
                            CourseId = 15,
                            Created = new DateTime(2021, 9, 1, 3, 40, 0, 0, DateTimeKind.Unspecified),
                            Email = "Ignatova38@gmail.com",
                            FirstName = "Екатерина",
                            LastName = "Игнатова",
                            Phone = "+375441183830",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Comments = "",
                            CourseId = 9,
                            Created = new DateTime(2021, 9, 1, 3, 40, 0, 0, DateTimeKind.Unspecified),
                            Email = "Timoshin3348@gmail.com",
                            FirstName = "Александр",
                            LastName = "Тимошин",
                            Phone = "+375441183334",
                            Type = 1
                        });
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkExperience")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Area of interest: development of web applications based on Sitecore, ASP.NET MVC / .NET Core and mobile applications using the Xamarin cross-platform framework; Sitecore JavaScript Services (JSS); the introduction of search engines such as Solr, Coveo; using cloud Azure solutions.",
                            Email = "teacher@mail.ru",
                            FirstName = "Вадим",
                            LastName = "Папко",
                            Phone = "+375291133322",
                            WorkExperience = "5 years"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Area of interest: development of web applications in ASP.NET MVC using JavaScript libraries (Angular, JQuery), API, microservices, Data Science, Machine Learning. Agile software development methodologies (Agile, Scrum, Kanban, Lean).",
                            Email = "DmitriyAlhimovich@gmail.com",
                            FirstName = "Дмитрий",
                            LastName = "Альхимович",
                            Phone = "+375293322211",
                            WorkExperience = "10 years"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Area of interest: optimization, programming of gameplay systems.",
                            Email = "RostislavNikishin@gmail.com",
                            FirstName = "Ростислав",
                            LastName = "Никишин",
                            Phone = "+375441188800",
                            WorkExperience = "4 years"
                        });
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ONX.CRM.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ONX.CRM.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ONX.CRM.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ONX.CRM.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.Course", b =>
                {
                    b.HasOne("ONX.CRM.DAL.Models.Specialization", "Specialization")
                        .WithMany("Courses")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.Group", b =>
                {
                    b.HasOne("ONX.CRM.DAL.Models.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("CourseId");

                    b.HasOne("ONX.CRM.DAL.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.Lesson", b =>
                {
                    b.HasOne("ONX.CRM.DAL.Models.Group", null)
                        .WithMany("Lessons")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.Student", b =>
                {
                    b.HasOne("ONX.CRM.DAL.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.StudentRequest", b =>
                {
                    b.HasOne("ONX.CRM.DAL.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.Course", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.Group", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("ONX.CRM.DAL.Models.Specialization", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
